apiVersion: v1
kind: Pod
metadata:
  name: netshoot-without-pid-net-ipc-access-pod
spec:
  containers:
  - name: netshoot-without-pid-net-ipc-access-pod
    image: angadisachin2/netshoot
    command: [ "bash", "-c", "sleep 5h" ]
    volumeMounts:
    - mountPath: /var/run/
      name: docker-sock
      # readOnly: true
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/
      type: Directory
